name: seamlesscast
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - pip:
      - opencv-python
      - PySide6
      - moderngl
      - imageio
      - imageio-ffmpeg
      - screeninfo